# Project Information
site_name: GiantPandaCV
site_description: GiantPandaCV
site_author: GiantPandaCV
site_url: http://giantpandacv.com


# Copyright
copyright: 'Copyright &copy; GiantPandaCV Team <a href="http://beian.miit.gov.cn">蜀ICP备2020031210号</a> '

# Contents
nav:
    - 首页:
        - Getting Started: index.md
        - GiantPandaCV 简介: introduction/introduction.md
    - academic:
        - 超分和GAN:
            - 专栏介绍: academic/超分和GAN/README.md
            - CVPR2020-NTIRE MSFSR A Multi-Stage Face Super-Resolution Network: academic/超分和GAN/CVPR2020-NTIRE MSFSR A Multi-Stage Face Super-Resolution Network.md
            - DeepFake系列之FakeSpotter: academic/超分和GAN/DeepFake系列之FakeSpotter.md
            - 基于Kaggle DeepFake比赛的代码实战: academic/超分和GAN/基于Kaggle DeepFake比赛的代码实战.md
            - 生成对抗网络中的数据增广：一种可微分的数据增广方法: academic/超分和GAN/生成对抗网络中的数据增广：一种可微分的数据增广方法.md
            - 仅使用少量数据训练生成对抗网络: academic/超分和GAN/仅使用少量数据训练生成对抗网络.md
            - Deblurring by Realistic Blurring 图像去模糊论文解读: academic/超分和GAN/Deblurring by Realistic Blurring 图像去模糊论文解读.md
            - 基于GAN来做低光照图像增强，EnlightenGAN论文解读: academic/超分和GAN/基于GAN来做低光照图像增强，EnlightenGAN论文解读.md
        - 传统图像: 
            - 专栏介绍: academic/传统图像/README.md
            - 一些有趣的图像算法: 
                - OpenCV图像处理专栏一  盘点常见颜色空间互转: academic/传统图像/一些有趣的图像算法/OpenCV图像处理专栏一  盘点常见颜色空间互转.md
                - OpenCV图像处理专栏二 《Local Color Correction 》论文阅读及C++复现: academic/传统图像/一些有趣的图像算法/OpenCV图像处理专栏二 《Local Color Correction 》论文阅读及C++复现.md
                - OpenCV图像处理专栏三  灰度世界算法原理和实现: academic/传统图像/一些有趣的图像算法/OpenCV图像处理专栏三  灰度世界算法原理和实现.md
                - OpenCV图像处理专栏四  自动白平衡之完美反射算法原理及C++实现:  academic/传统图像/一些有趣的图像算法/OpenCV图像处理专栏四  自动白平衡之完美反射算法原理及C++实现.md
                - OpenCV图像处理专栏五  《Real-time adaptive contrast enhancement for imaging sensors》论文解读及实现: academic/传统图像/一些有趣的图像算法/OpenCV图像处理专栏五  《Real-time adaptive contrast enhancement for imaging sensors》论文解读及实现.md
                - OpenCV图像处理专栏六  来自何凯明博士的暗通道去雾算法(CVPR 2009最佳论文): academic/传统图像/一些有趣的图像算法/OpenCV图像处理专栏六  来自何凯明博士的暗通道去雾算法(CVPR 2009最佳论文).md
                - OpenCV图像处理专栏七  直方图均衡化算法及代码实现: academic/传统图像/一些有趣的图像算法/OpenCV图像处理专栏七  直方图均衡化算法及代码实现.md
                - OpenCV图像处理专栏八   《Contrast image correction method》 论文阅读及代码实现: academic/传统图像/一些有趣的图像算法/OpenCV图像处理专栏八   《Contrast image correction method》 论文阅读及代码实现.md
                - OpenCV图像处理专栏九  基于直方图的快速中值滤波算法: academic/传统图像/一些有趣的图像算法/OpenCV图像处理专栏九  基于直方图的快速中值滤波算法.md
                - OpenCV图像处理专栏十  利用中值滤波进行去雾: academic/传统图像/一些有趣的图像算法/OpenCV图像处理专栏十  利用中值滤波进行去雾.md
                - OpenCV图像处理专栏十一  IEEE Xplore 2015的图像白平衡处理之动态阈值法: academic/传统图像/一些有趣的图像算法/OpenCV图像处理专栏十一  IEEE Xplore 2015的图像白平衡处理之动态阈值法.md
                - OpenCV图像处理专栏十二 《基于二维伽马函数的光照不均匀图像自适应校正算法》: academic/传统图像/一些有趣的图像算法/OpenCV图像处理专栏十二 《基于二维伽马函数的光照不均匀图像自适应校正算法》.md
                - OpenCV图像处理专栏十三  利用多尺度融合提升图像细节: academic/传统图像/一些有趣的图像算法/OpenCV图像处理专栏十三  利用多尺度融合提升图像细节.md
                - OpenCV图像处理专栏十四  基于Retinex成像原理的自动色彩均衡算法(ACE): academic/传统图像/一些有趣的图像算法/OpenCV图像处理专栏十四  基于Retinex成像原理的自动色彩均衡算法(ACE).md
                - OpenCV图像处理专栏十五 《一种基于亮度均衡的图像阈值分割技术》: academic/传统图像/一些有趣的图像算法/OpenCV图像处理专栏十五 《一种基于亮度均衡的图像阈值分割技术》.md
                - OpenCV图像处理专栏十六  合理选用Side Window Filter辅助矩形框检测: academic/传统图像/一些有趣的图像算法/OpenCV图像处理专栏十六  合理选用Side Window Filter辅助矩形框检测.md
                - OpenCV图像处理专栏十七  清华大学《基于单幅图像的快速去雾》C++复现（有一定工程意义）: academic/传统图像/一些有趣的图像算法/OpenCV图像处理专栏十七  清华大学《基于单幅图像的快速去雾》C++复现（有一定工程意义）.md
                - OpenCV图像处理专栏十八  手动构造Sobel算子完成边缘检测: academic/传统图像/一些有趣的图像算法/OpenCV图像处理专栏十八  手动构造Sobel算子完成边缘检测.md
                - OpenCV图像处理专栏十九  手动实现基于Canny算子的边缘检测: academic/传统图像/一些有趣的图像算法/OpenCV图像处理专栏十九  手动实现基于Canny算子的边缘检测.md
                - OpenCV图像处理专栏二十 《Adaptive Logarithmic Mapping For Displaying High Contrast Scenes》复现: academic/传统图像/一些有趣的图像算法/OpenCV图像处理专栏二十 《Adaptive Logarithmic Mapping For Displaying High Contrast Scenes》复现.md
                - 《Optimized contrast enhancement for real-time image and video dehazin》论文C++复现: academic/传统图像/一些有趣的图像算法/《Optimized contrast enhancement for real-time image and video dehazin》论文C++复现.md
                - 《Single Image Haze Removal Using Dark Channel Prior》论文阅读及复现番外: academic/传统图像/一些有趣的图像算法/《Single Image Haze Removal Using Dark Channel Prior》论文阅读及复现番外(使用导向滤波估计更加精细的透射率).md
                - 《改进非线性亮度提升模型的逆光图像恢复》论文复现: academic/传统图像/一些有趣的图像算法/《改进非线性亮度提升模型的逆光图像恢复》论文复现.md
                - CVPR论文《100+ Times Faster Weighted Median Filter (WMF)》的实现和解析: academic/传统图像/一些有趣的图像算法/CVPR论文《100+ Times Faster Weighted Median Filter (WMF)》的实现和解析.md
            - 一些基础的图像算法:
                - 《Adaptive Local Tone Mapping Based on Retinex for High Dynamic Range Images》C++实现: academic/传统图像/一些基础的图像算法/《Adaptive Local Tone Mapping Based on Retinex for High Dynamic Range Images》C++实现.md
                - RGB和CIELAB颜色空间转换及偏色检测: academic/传统图像/一些基础的图像算法/RGB和CIELAB颜色空间转换及偏色检测.md
                - 肤色检测算法 - 基于不同颜色空间简单区域划分的皮肤检测算法: academic/传统图像/一些基础的图像算法/肤色检测算法 - 基于不同颜色空间简单区域划分的皮肤检测算法.md
                - 高斯滤波的C++实现与优化: academic/传统图像/一些基础的图像算法/高斯滤波的C++实现与优化.md
                - 基于二次多项式混合模型肤色检测算法: academic/传统图像/一些基础的图像算法/基于二次多项式混合模型肤色检测算法.md
                - 色彩均衡化算法: academic/传统图像/一些基础的图像算法/色彩均衡化算法.md
                - 双边滤波原理及Opencv调用: academic/传统图像/一些基础的图像算法/双边滤波原理及Opencv调用.md
                - 同态滤波 原理及实现: academic/传统图像/一些基础的图像算法/同态滤波 原理及实现.md
                - 图像处理中的分水岭算法: academic/传统图像/一些基础的图像算法/图像处理中的分水岭算法.md
                - 图像处理中的模糊算法: academic/传统图像/一些基础的图像算法/图像处理中的模糊算法.md
                - 图像处理中的锐化算: academic/传统图像/一些基础的图像算法/图像处理中的锐化算法.md
                - 引导滤波 原理及实现: academic/传统图像/一些基础的图像算法/引导滤波 原理及实现.md
    

# Theme
theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'white'
    accent: 'red'
    scheme: preference
    
  icon:
    logo: 'material/school'
  features:
    - navigation.tabs
  font:
    text: 'Noto Sans'
    code: 'Source Code Pro'

# Customization
extra:
  search:
    language: 'jp'
  disqus: 'GiantPandaCV'
  copyright: 'CC BY-NC-SA 4.0'

extra_javascript:
    - 'https://cdnjs.loli.net/ajax/libs/pangu/3.3.0/pangu.min.js'
    - '_static/js/extra.js'
    - 'https://cdnjs.loli.net/ajax/libs/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'

extra_css:
    - '_static/css/extra.css'

# Extensions
markdown_extensions:
    - admonition
    - codehilite:
        guess_lang: false
    - def_list
    - footnotes
    - meta
    - toc:
        permalink: true
    - pymdownx.arithmatex
    - pymdownx.caret
    - pymdownx.critic
    - pymdownx.details
    - pymdownx.emoji:
        emoji_generator: !!python/name:pymdownx.emoji.to_svg
    - pymdownx.inlinehilite
    - pymdownx.keys
    - pymdownx.magiclink
    - pymdownx.mark
    - pymdownx.smartsymbols
    - pymdownx.superfences
    - pymdownx.tasklist:
        custom_checkbox: true
    - pymdownx.tilde
