name: mkdocs update
on:
  push:
    branches: [ main ]
  pull_request:
    types: [closed]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Connect to server
        uses: appleboy/ssh-action@master
        with:
          host: 123.57.73.246
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
      - name: Run script
        run: |
          ./root/zdby.sh 
