name: mkdocs update
on:
  push:
    branches: [ master ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Connect to server
        uses: appleboy/ssh-action@master
        with:
          host: 123.57.73.246
          username: root
          key: ${{ secrets.FTQ2 }}
          port: 22
          command_timeout: 200m
          script: |
            bash /root/git_pull.sh
            bash /root/bs.sh
